//################################################################################# 
// 
// 
// FILE:   cpu1brom_ubgpio.h
// 
// TITLE: Unbonded GPIO Pin Pullup values for F280013x BootROM 
// 
// (Auto-Generated by Unbonded GPIO tool found at <parent_dir>/tools/unbonded_gpio) 
//################################################################################# 
//  $TI Release: F280013x Boot ROM V1.0 $ 
//  $Release Date: March, 2021 $ 
//  $Copyright:
// Copyright (C) 2022 Texas Instruments Incorporated - http://www.ti.com
//
// Redistribution and use in source and binary forms, with or without 
// modification, are permitted provided that the following conditions 
// are met:
// 
//   Redistributions of source code must retain the above copyright 
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the 
//   documentation and/or other materials provided with the   
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// $ 
//################################################################################# 

#ifndef CPU1BROM_UBGPIO_H
#define CPU1BROM_UBGPIO_H

// TOPOARIA_64_QFP_PM_VREGENZ
// Unbonded GPIOs: 39,
#define TOPOARIA_64_QFP_PM_VREGENZ_GPA             0xFFFFFFFFUL
#define TOPOARIA_64_QFP_PM_VREGENZ_GPB             0xFFFFFF7FUL

// TOPOARIA_64_QFP_PM
// Unbonded GPIOs: None
#define TOPOARIA_64_QFP_PM_GPA                     0xFFFFFFFFUL
#define TOPOARIA_64_QFP_PM_GPB                     0xFFFFFFFFUL

// TOPOARIA_48_QFP_PT
// Unbonded GPIOs: 8,9,10,11,17,20,21,22,23,39,40,41,
#define TOPOARIA_48_QFP_PT_GPA                     0xFF0DF0FFUL
#define TOPOARIA_48_QFP_PT_GPB                     0xFFFFFC7FUL

// TOPOARIA_48_QFN_RGZ
// Unbonded GPIOs: 10,11,17,20,21,22,39,40,41,
#define TOPOARIA_48_QFN_RGZ_GPA                    0xFF8DF3FFUL
#define TOPOARIA_48_QFN_RGZ_GPB                    0xFFFFFC7FUL

// TOPOARIA_32_QFN_RTM
// Unbonded GPIOs: 2,6,8,9,10,12,13,16,17,20,21,22,
//                 23,23,33,39,40,41,
#define TOPOARIA_32_QFN_RTM_GPA                    0xFF0CC8BBUL
#define TOPOARIA_32_QFN_RTM_GPB                    0xFFFFFC7DUL

#endif
